version: "3.2"
services:

    nginx:
        image: nginx:latest
        ports:
            - 80:80
            - 443:443
        volumes:
            - ../:/var/www/search-states
            - ./nginx/app-search-states.conf:/etc/nginx/conf.d/default.conf

    search-states-php81:
        build: php81
        volumes:
            - ../:/var/www/search-states
        working_dir: /var/www/search-states
        ports:
            - 9074:9000
        extra_hosts:
            - "host.docker.internal:host-gateway"

    redis:
        image: redis
        ports:
            - 6379:6379

networks:
    minha-rede:
        ipam:
            config:
                - subnet: 172.20.0.0/16
